### ISSUE TITLE
Notification authorization status is not always up-to-date when app comes to foreground

### ISSUE THREAD

**Issue by JGanol** [Notificare/notificare-sdk-ios#24]
Hi guys,

I am testing Notificare v3.2.0, and noticed that sometimes the SDK doesn't trigger event `func notificare(_ notificarePush: NotificarePushKit.NotificarePush, didChangeNotificationSettings granted: Bool)` when an App returns to foreground (and a user changed permissions for notifications via Settings). Is it something I should count on, or should update on my side and push the SDK to re-register/unregister?

Kind regards

**Comment by JGanol** [comment]
The scenario i have is the following:
1. Launching Notificare SDK: notificare.launch() + registering delegates
2. Waiting for SDK to be ready (listening to delegate be called)
3. A user is registering for notifications: notificare.push().enableRemoteNotifications()
4. A user is registering a device: notificare.device().register(userId: some_id, userName: some_name)
5. Getting an event that authorization status has been changed to Granted.
6. Now notifications are successfully received, all works fine.
7. The App goes to background, and a user changes authorization status to Denied.
8. The App comes back to foreground.
9. Delegate is called to notify that authorization status has changed, and it is now Denied.
10. I do unregistering device and unregistering from notifications: notificare.push().disableRemoteNotifications() and notificare.device().register(userId: nil, userName: nil).
11. Now as expected I don't receive notifications.
12. The App goes to background, and a user changes authorization status back to Granted via Settings.
13. The App goes to foreground.

Expected behaviour: the app is notified about authorization status change and registers the user again.

Actual behaviour: the app doesn't get any notification about this change. And delegate is assigned and is not accidentally deallocated (to answer your first assumption). There are no settings switching twice. The network is stable. The issue is replicable, which also excludes network issues.

**Comment by JGanol** [comment]
Good question. So if I just register a device for notifications, Notificare SDK will take of permissions and actual sending? And a logical reason to unregister a device will be when a user logs out?

**Comment by hpinhal** [comment]
That's right. When you call `enableRemoteNotification()`, we take care of registering with APNS, triggering the permission prompt and reporting the response.

Depending on your use case, when the user logs out, you can `register(userId: nil, userName: nil)` to remove the association with the user. This doesn't disable remote notifications as you may want to engage anonymous devices. However, nothing prevents you from doing so.

**Comment by JGanol** [comment]
Thank you, Helder. Now it is clear to me!
